logLevel := Level.Warn
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.5")
//addSbtPlugin("org.scala-debugger" % "sbt-scala-debugger" % "1.1.0-M3")
//addSbtPlugin("org.scala-debugger" % "sbt-jdi-tools" % "1.0.0")
//addSbtPlugin("org.senkbeil" %% "sbt-grus" % "0.1.0")
//addSbtPlugin("org.scala-debugger" %% "sbt-scala-debugger" % "1.1.0-M3")
//addSbtPlugin("com.typesafe.sbt" % "sbt-proguard" % "0.2.2")
//addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.0")
//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M14-3")
